### ISSUE TITLE
sso-proxy: websocket support

### ISSUE THREAD

**Issue by stephen** [buzzfeed/sso#103]
**Is your feature request related to a problem? Please describe.**
I did a readthrough of the proxy code and believe that there is no support for websockets, since `httputil.ReverseProxy` does not support websockets out of the box. It would be great to add them.

**Describe the solution you'd like**
Let's add websocket support. It'd look roughly like this: https://github.com/samsarahq/oauth2_proxy/pull/1/files#diff-6fd8df33d9f8086bc31e28c375fbc0abR99

**Describe alternatives you've considered**
I didn't consider an alternative apart from not using this library.

**Additional context**
n/a

**Comment by komljen** [comment]
Any updates on this?

**Comment by sonicsnes** [comment]
I needed to hack this together real quick for personal use. If you
* use go >= v1.12 (which has native websocket reverse proxy support)
* add this to each of your upstream `default` configs:
```
options:
  flush_interval: 100ms
```
* In cmd/sso-proxy/main.go, change
```
Handler:      proxy.NewLoggingHandler(os.Stdout, oauthproxy.Handler(), opts.RequestLogging, oauthproxy.StatsdClient)
```
to
```
Handler:      oauthproxy.Handler()
```

Then request logging will no longer work, but websockets will proxy just fine. This is because go requires all handlers to implement `Hijacker` to proxy websockets, but the logging handler doesn't do this. It was easier for me to just remove logging rather than fix it.

Good luck!

**Comment by komljen** [comment]
Thanks, I already tried to use 1.12 but didn't make those additional changes.
I will give it a shot.

**Comment by komljen** [comment]
Unfortunately, that hack didn't work in my case...

**Comment by sonicsnes** [comment]
If you've already removed the NewLoggingHandler, make sure that you've put the flush_interval options in the correct place. I think if you put it on the wrong level of the yml, it won't complain but it also won't do anything.

**Comment by komljen** [comment]
I think I did, here is one example:

```
    - default:
        from: k8s.example.com
        to: http://kubernetes-dashboard.default.svc.cluster.local:443
        options:
          allowed_groups:
          - team@example.com
          flush_interval: 100ms
      service: kubernetes-dashboard
```

I tried the change on both master and 1.1.0 branches, got the same errors.
When accessing one endpoint, this is the error in web console:
```
failed: Error during WebSocket handshake: Unexpected response code: 502
```

On another endpoint I get different error:
```
failed: Error during WebSocket handshake: Unexpected response code: 403
```

I will probably move to https://github.com/pusher/oauth2_proxy which supports websockets. I already spent too much time on this and I don't think anyone will make a proper implementation anytime soon.

Thanks for your help!

**Comment by camerondavison** [comment]
im 100% surprised that this is not working. https://github.com/bitly/oauth2_proxy/pull/145#issuecomment-148406451 websockets has been one of the open issues for a while from oauth2 even.

any idea if this is on a roadmap of any kind?

**Comment by komljen** [comment]
@camerondavison use this fork if you want to check oauth proxy https://github.com/pusher/oauth2_proxy. It has support for WebSockets. Bitly is deprecated.

**Comment by cameronattard** [comment]
+1 for this. We really need this feature.

**Comment by JohnlNguyen** [comment]
Correct me if I'm wrong but I thought websocket support is in go 1.12 
`https://go-review.googlesource.com/c/go/+/146437/`.

**Comment by komljen** [comment]
Yes, it is, but someone needs to update the code so we can use it in auth proxy.
Just building with go 1.12 is not enough.

**Comment by rlabrecque** [comment]
If anyone's finding this since, WebSocket support is working, but you explicitly still need the:

```options:
  flush_interval: 100ms```

**Comment by Jusshersmith** [comment]
Thanks @rlabrecque! Apologies if this hasn't been made clear enough. It was also added to the [documentation](https://github.com/buzzfeed/sso/blob/a3c8a2ad4584bc546871633cc0391336c3acfd5a/docs/sso_config.md#websockets), just in case anyone comes by this.
