### ISSUE TITLE
Quickstart example code references a non-existent docker project

### ISSUE THREAD

**Issue by Integralist** [buzzfeed/sso#104]
**Describe the bug**
Following along with the quickstart guide I discovered a reference to a docker hub account that appears to no longer exist.

**To Reproduce**
Attempt to start up containers using docker-compose:
1. `cd quickstart && docker-compose up -d`

**Expected behavior**
An example application to be started and pre-configured.

**Screenshots**
![screen shot 2018-10-30 at 5 08 05 pm](https://user-images.githubusercontent.com/180050/47736318-625f7c80-dc66-11e8-98f8-13e586995126.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Additional context**
If I search Google for `tutum/hello-world` (which is referenced in the `docker-compose.yml`) I find a link to https://hub.docker.com/r/tutum/hello-world/ which returns a 404.

Searching for the tutum account in Docker Hub yields no 'hello-world' results, so it appears to indeed have been removed. There is an 'official' hello-world, but it's unclear what the expectation is for this example: https://hub.docker.com/_/hello-world/.

**Comment by danbf** [comment]
@Integralist @loganmeetsworld 

quickstart for me does indeed pull down a valid image.  it looks like it was a glitch in the matrix as https://hub.docker.com/r/tutum/hello-world/ also works for me.  can you confirm and close this issue if things are work?

```
Pulling hello-world (tutum/hello-world:latest)...
latest: Pulling from tutum/hello-world
658bc4dc7069: Pull complete
a3ed95caeb02: Pull complete
af3cc4b92fa1: Pull complete
d0034177ece9: Pull complete
983d35417974: Pull complete
Digest: sha256:0d57def8055178aafb4c7669cbc25ec17f0acdab97cc587f30150802da8f8d85
Status: Downloaded newer image for tutum/hello-world:latest
```

**Comment by Integralist** [comment]
Interesting that link is working now 🤔 I'll check in the morning and close if it works 👍

**Comment by Integralist** [comment]
Going to close this issue. Seems that Docker Hub must have had an issue where by that hello-world app was no longer available. But it is now back again so 🤷‍♂️
