### ISSUE TITLE
sso-auth: encrypt-then-MAC

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#11]
In auth/payloads/payloads.go, ensure that you [encrypt-then-mac](https://crypto.stackexchange.com/questions/202/should-we-mac-then-encrypt-or-encrypt-then-mac) cookie strings.

**Comment by mreiferson** [comment]
> We kept the old code paths in for cookies that had not yet expired but we are planning to remove those old code paths soon.

@shrayolacrayon have these code paths been removed? If so, let's close this.

**Comment by shrayolacrayon** [comment]
Yes, these code paths have been removed. Closing this issue!
