### ISSUE TITLE
sso-{auth,proxy}: support per-service long-lived bearer tokens

### ISSUE THREAD

**Issue by bertjwregeer** [buzzfeed/sso#127]
**What I would like**

There are certain sites that are also accessed programmatically by internal users, and I would like to continue supporting that use case while providing an audit trail and logging.

I'd like some way for a user to get a per-service bearer token that they can use in their local scripts to make HTTP requests against a service that is protected by sso-proxy.

As an example, we've got a pastebin service we would like to secure with oauth2 through Gsuite when accessing it from your browser, but we've also got some scripts that we can run from the command line to quickly paste to pastebin/get a link to said paste to drop into Slack for instance.

It'd would be nice if users could go to sso-auth and get a bearer token that is tied to their Gsuite account (and if their account is disabled, or they are removed from the pastebin group, that said token is no longer valid) and continue to use the script workflow without forcing users to use a browser.

**Describe alternatives you've considered**

Right now those services sit behind Basic HTTP auth and allows passing of a "well known" username/password to the URL and we use NGINX to allow/deny access, but this doesn't give us the traceability I would like from a security perspective. Anyone that knows the username/password can gain access... and credential rotation is a nightmare as it is hardcoded in so many places.

----

Unless I missed it, currently you'd have to copy/paste your cookie value and make sure to keep it updated as it changes, and there is no good way to go through the various redirect hoops from Python or some other scripting language to get access to that cookie value.

**Comment by mreiferson** [comment]
Hi @bertjwregeer, thanks for opening this issue!

We've talked about similar use-cases here at BuzzFeed and I agree this would be something interesting to consider for SSO.

I'm curious what @jphines thinks?

**Comment by katzdm** [comment]
Hey Bert, thanks for the feature request! I have some concerns around the implementation of such tokens, particularly around their "long-lived"-ness.

Off the top of my head, there are two obvious directions for implementation of such a token:

1. **Pseudorandomly-generated opaque identifiers**: These would need to be tracked in a datastore of some sort, which would add significant complexity to SSO, and might not scale super well.

2. **Data-bearing ciphertext**: My concern here is that any encryption-based token will become necessarily invalidated in the event of a  master-key rotation within SSO. One would expect for any such token to become hardcoded in various scripts and cron-jobs within an organization (indeed, that's the use case you have in mind), leading to unknown (and potentially large) breakages following a key-rotation event.

One possible workaround would be to implement a "refresh"-protocol similar to OAuth2 itself, in which a token can be refreshed/exchanged for a new token. SSO would then "remember" old master-keys until the maximum "refresh"-period expires, after which the old key is permanently "forgotten." The immediate issue here is that this invalidates "ad-hoc" scripts and infrequently-running cron-jobs, which might be run less than once per day (even once per week). Any protocol allowing for a "limited timeframe refresh" would have limited utility for the use-case you seem to have in mind (if I understand your request correctly).

But maybe we're okay with tokens expiring in the event of a key-rotation! If that's the case, then we might consider explicitly guarding against long-lived token lifetime dependencies, by aggressively limiting the lifespan of a token (say, 48hrs). This might allow for a "lease" long enough to perform useful work, but short enough to antagonistically break systems that attempt to establish a long-lived dependency on a token (e.g. tokens committed to source control).

A final concern thought is whether this functionality belongs in SSO itself, as it represents a significant expansion of scope for the project. SSO already supports lists of per-service endpoints that don't require authentication (i.e. "allow all traffic" via `skip_auth_regex` in the upstream config file). Perhaps you might have two endpoints for your web service: One which issues API tokens (`/get-token`), and one which provides a service (`/api`). You might then configure SSO to authenticate all traffic accessing the `/api` endpoint such that only authenticated users can generate an API token, but allow all traffic through on the `/api` endpoint. The token-validation logic could then be offloaded to the application itself, rejecting all requests that do not include a valid API token.

What do you think? Let me know if there's an obvious long-lived token implementation option that I've overlooked, or if you think that the suggested application-generated token scheme might work for your use-case.

**Comment by bertjwregeer** [comment]
1. I'd be okay with a database of some sort to store these tokens, ultimately I am using SSO to protect some applications that are not even user aware, but is internal infrastructure. The pastebin example was just one such case, but there are plenty of others where there is a status page that I would like to protect and yet still have available on the WWW without needing to first jump through some bastion host using VPN/SSH. I'm small fish... in my case I don't expect a massive load, and it's about ~15 or so users. Those same status pages/other API's are not auth aware but I still want to protect them, that's why this project drew me to it.
2. If I am doing key rotation on the SSO I would expect all tokens to become invalidated anyway. Anything in cron jobs/other places like that would become invalidated immediately which is excellent. Good security hygiene and means that you don't become complacent when it comes to rotation of credentials.

If the tokens can be refreshed programmatically that would be fantastic. If the default is that a refresh token is valid for 12 hours, I'll happily run a small cron job every 3 hours to refresh the token and then the actual script that does the heavy lifting runs once a day and uses the saved token.

> antagonistically break systems that attempt to establish a long-lived dependency on a token (e.g. tokens committed to source control).

I'm a huge proponent of this. Long lived keys make life easier for attackers, and make security engineering a nightmare :P Making it harder to store tokens in source control but easy enough to refresh on schedule is perfect.

>  SSO already supports lists of per-service endpoints that don't require authentication (i.e. "allow all traffic" via skip_auth_regex in the upstream config file). Perhaps you might have two endpoints for your web service: One which issues API tokens (/get-token), and one which provides a service (/api). You might then configure SSO to authenticate all traffic accessing the _/get-token_ endpoint such that only authenticated users can generate an API token, but allow all traffic through on the /api endpoint. The token-validation logic could then be offloaded to the application itself, rejecting all requests that do not include a valid API token.

Some of the things I am looking to protect, yet still allow scriptable access to are a specific use case, so feel free to outright reject this idea, but here is one thing that I am hoping to protect that is a tool that admins use, but is not browser accessed:

We use AWS to automatically spin up and down new machines, when we do that we update an ec2-hosts text file that is located on a server at a well known URL. Right now that is protected by HTTP Basic auth. It's a text file, and doesn't need to be anything more since it's updated by an external process and plopped on that server... but we have a tool that allows an admin to run something like:

```
connectto dbserver --tag=master
```

it downloads said ec2-hosts file, looks at all of the dbservers, and then looks for the one tagged as master, and connects to it using an SSH bastion host, automatically setting up the right SSH keys/forwarding and all that fun stuff.

This `connectto` script would require said long-lived token. I'd want the token to be aggressively refreshed, but to last maybe ~4 days or so. This way an admin that likely has a use for `connectto` daily gets new tokens often enough that they are not inconvenienced (and if they don't work the weekend... unlikely with those of us on call) when they haven't had a chance to refresh the token, but a user that uses it less gets a browser window popped that allows them to re-auth against SSO and grab a new token.

As I mentioned, the `ec2-hosts` is just a file. Writing an application around it just to provide long-lived API tokens to bypass SSO really feels like I am getting rid of what SSO can provide for me. Especially invalidation of those tokens in a central location based upon the Gsuite user being active/in certain groups/things of that nature.

My whole goal is to off-load all of this into a single well controlled application so that key rotation becomes easy and centralised in case of compromise or a users laptop being stolen vs doing that ad-hoc in each application hosted behind the sso-proxy.

**Comment by katzdm** [comment]
Hi Bert - Thanks for elaborating on your use case! After some discussion, we feel that this feature is outside the current intended scope of SSO. We are generally wary of any solution that requires a persistent data store, so any proposal for such a component is unlikely to be considered.

If you want to get something like this going quickly, then you might consider deploying a simple service similar to the one I described above, which provides tokens via an SSO-fronted endpoint; tokens might be generated by encrypting `(X-Forwarded-User, Timestamp)`-pairs and returning the result to the browser as base64-encoded ciphertext. A separate unauth'd-endpoint can then validate the token and serve the requested pages if it's valid. Perhaps such a service could validate the decrypted token against a central file containing revoked tokens, prior to serving any content - A list of `(User, Timestamp)`-pairs might indicate "Do not accept any tokens from `User` which were generated prior to `Timestamp`". The existing HTTP libraries provided by Go's standard library would provide a solid foundation and starting point for such a service.

Sorry we couldn't be of more help. I hope that SSO is still able to provide value within your service ecosystem!

**Comment by bertjwregeer** [comment]
Not unexpected, thanks!
