### ISSUE TITLE
Update formatting of Google OAuth2 URLs

### ISSUE THREAD

**Issue by katzdm** [buzzfeed/sso#131]
**Describe the bug**
`sso_auth` currently formats Google OAuth2 URLs with the parameter:
`approval_prompt=<o.ApprovalPrompt>`,
where `o.ApprovalPrompt` defaults to the value `"force"`. According to [this thread](https://github.com/googleapis/oauth2client/issues/453), this behavior was deprecated in 2016 (this is likely legacy the Bitly proxy). We should instead format our URLs with the parameter `prompt=<o.ApprovalPrompt>`, where `o.ApprovalPrompt` should instead default to the value `"consent"`.

**Expected behavior**
URLs use `prompt=consent` instead of legacy `approval_prompt=force`. No expected change in behavior to user flow.

Example current URL:
`https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=[...]`

Desired URL:
`https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent&client_id=[...]`

**Comment by Jusshersmith** [comment]
👋 Thanks for submitting this - I believe it’s been resolved in https://github.com/buzzfeed/sso/pull/216, along with a change to how the configuration variables are configured in previous changes. 

The previous ‘default’ no longer exists, and is instead set to ‘consent’ if not already set (effectively acting as the default, just in a different place)
