### ISSUE TITLE
sso-auth: Members in a group within a group don't validate

### ISSUE THREAD

**Issue by bertjwregeer** [buzzfeed/sso#133]
I've setup group validation using Gsuite, and that is working correctly, however my groups may contain other groups (to build an easier hierarchy).

It seems that when a group contains one or more other groups, that sso-auth does not traverse down into those other groups to validate if the user is a member of those. In the mean time I've added those additional groups to the sso-proxy configuration, but I would prefer to be able to use the nesting mechanism already present in Gsuite.

**To Reproduce**
1. Create new group in Gsuite
2. Add a group as member in that new group created in 1
3. Add the new group created in 1 as the `allowed_groups` in sso-proxy's upstream config
4. Notice that a user that is in the sub-group is not granted access to the resource

**Expected behavior**

I would expect sso-auth to traverse the groups found within a group for a match too.

**Comment by shrayolacrayon** [comment]
Thank you for opening this @bertjwregee, I'm glad you were able to find a workaround for this issue.  We will work on figuring out when we can prioritize getting this work done, and always appreciate contributions!

**Comment by bertjwregeer** [comment]
@shrayolacrayon Unfortunately my Go programming is not nearly as strong as my Python. I don't feel comfortable diving in and making this change.

**Comment by loganmeetsworld** [comment]
We've talked about it a bit amongst maintainers and have a few concerns and have concluded that, while it's an interesting issue, we are not looking to prioritize it at this time.

The first concern is security. We fear this might obfuscate membership within groups and possibly lead to a public or open group being nested unwittingly. 

The second concern is complexity of implementation. How far are we intending to nest groups? What about accidentally entering a recursive nested with groups of groups being groups of other groups? I'm definitely open to ideas about cutoffs for that type of nesting, but can see things getting tricky. We are also ensure of how this would impact our caching of groups, but that is a lesser concern than the depth of the nest.

**Comment by bertjwregeer** [comment]
I can understand the security concerns, and I can understand the looping concerns.

At the same time it now shifts the burden of granting access from HR, who can add/remove users from the sub-groups as necessary and add groups to the top-level group to an administrator/devops/deployment.

Instead of HR being able to re-organise how they see fit, if they add a new group with members a new ticket has to be created to make sure that group gets added to the allowed list in the SSO proxy. Old groups now also need to be removed or made sure that they never overlap in the future with a previous group.

It all adds up to more mental overhead. Nesting of groups is supported by Google for granting access to other resources already, and is a very natural thing to do in the LDAP world (think Active Directory). It was a surprise to me that the users in the nest groups didn't get access to the resource already because it seems like such a logical thing to do. Right now the documentation isn't clear on this at all either.

I would urge you to reconsider. Set a nesting limit (Google doesn't enforce one, and I am not sure how their API would react to a nested loop...) to 2 or something sane, cache those groups like the groups are currently cached.

None of our groups are nested more than twice deep at the moment, and we don't have any loops, so I am less worried about them, but even nested loops shouldn't matter to SSO since it just needs to build a list of users, and if it comes across a nested group it has already seen it can skip it.

**Comment by bertjwregeer** [comment]
>  We fear this might obfuscate membership within groups and possibly lead to a public or open group being nested unwittingly.

This is a concern that SSO Auth shouldn't be enforcing a particular view on. If someone creates a group that contains the "world" as it were, that is on them. Mistakes are going to be made.

Add all existing users in the org to a single group is already a feature that Google makes available... that's also a giant oopsie and SSO Auth doesn't protect me from that.

**Comment by loganmeetsworld** [comment]
Thanks for your response. We'll continue to spin this around the maintainers group, but to be clear – while we cannot make this a priority currently, we are not wholesale opposed to a community contribution for this feature.

**Comment by bertjwregeer** [comment]
@loganmeetsworld your initial response shut it down pretty hard, whether that was intentional or not. I can completely understand that it is not a priority, but before I try and find someone that may be able to work on this to solve our needs I would at least want to know that such a change would get accepted.

**Comment by loganmeetsworld** [comment]
@bertjwregeer my apologies for the confusion! I did mean to convey that while we can't prioritize this, we are open to contributions. But I also meant to communicate concerns that came up in our discussions around nested groups when we were first implementing group authentication (and hopefully give context around why that choice was made). 

> What about accidentally entering a recursive nested with groups of groups being groups of other groups? I'm definitely open to ideas about cutoffs for that type of nesting, but can see things getting tricky. 

was meant to start a discussion, not end it. We'd just like to see any proposed solutions address these concerns. 

I'll also amend the docs accordingly, thank you for pointing that out.

**Comment by katzdm** [comment]
Hey Bert! Our team has been discussing your feature request this morning. We seem to be converging towards the following position:

- We **are** open to having SSO support nested groups. Our team does not have the resources to prioritize the feature ourselves, but we're open to a community-led contribution.
- We would like for any implemented design to help users avoid "sharp corners" by disallowing potentially dangerous configurations and behaviors by default.
- We think that this feature needs some design work before any PR can be considered. This thread is an excellent place for that discussion to happen :-)

When I say that our design should help for users to "avoid sharp corners", I mean:

1. Allowing access to an upstream service based on membership of a public or open group
2. Concerns around maximal nesting-depth should be addressed

We would like for SSO's  *default* behavior to be to remove all public/open groups from the universe of access-granting groups; an environment variable (e.g. `SSO_RECOGNIZE_PUBLIC_GROUPS`) could allow for service ecosystem maintainers to explicitly override this safeguard. If we cannot ascertain the publicity/openness of a group from current group APIs (Google, Azure AD, etc), then we would rather err on the side of caution by making the entire "nested groups" feature enabled only through opt-in (e.g. `SSO_EXPAND_NESTED_GROUPS`). While your point that the misconfiguration of an IAM hierarchy by administrators is "on them" is well made, we're striving to make it easy for users to do the right thing and extra work to do the dangerous thing.

If you (or your colleagues) are able to dedicate some time to this, then we'd love to continue the conversation here. Let's start with some concrete suggestions for what this feature will look like, before moving towards a PR.

**Comment by jphines** [comment]
Fixed in https://github.com/buzzfeed/sso/pull/149

However, the feature as implemented has several sharp corners including a non-configurable max depth and makes no attempt to disambiguate potential cycles if they occur.
