### ISSUE TITLE
sso-auth/ sso-proxy remove SkipProviderButton field from options 

### ISSUE THREAD

**Issue by shrayolacrayon** [buzzfeed/sso#134]
We have an unused field `SkipProviderButton` that does not do anything and to reduce confusion should be removed. There is a related issue - #132, which is a feature request to add this functionality.

**Comment by Jusshersmith** [comment]
This was removed in https://github.com/buzzfeed/sso/pull/207/ - I'll close this for now, however the feature request to add it back with the intended functionality is still open!
