### ISSUE TITLE
Rewrite rules not working

### ISSUE THREAD

**Issue by J3tto** [buzzfeed/sso#155]
**Describe the bug**
The rewrite rules outlined in the docs at: [https://github.com/buzzfeed/sso/blob/master/docs/sso_config.md]
do not work, please you advise the syntax needed for rewrite rules to work.

**To Reproduce**
1. Using the sample in the docs provides the following error during starting the sso_proxy:
`{"error":"Invalid configuration:\n  error parsing upstream configs file unable to url parse `from` parameter error=parse https://^example-service-(.*).sso.sampledomain.com$: invalid character \"^\" in host name","level":"error","msg":"error validing opti
ons","service":"sso-proxy","time":"2019-02-08 11:26:38.2811"}`

Sample upstream file used:  (Layout is correct github just wont show code on multiline)
- service: example_service
  default:
    from: ^example-service-(.*).sso.sampledomain.com$
    to: example-service-$1.sampledomain.com`

**Comment by J3tto** [comment]
I've just seen the type property. Suggest updating the Docs/Example to actually include type was easily missed in copy and paste..

**Comment by loganmeetsworld** [comment]
Thanks for filing this ticket. I'm going to look into updating the docs to make sure this is clear.
