### ISSUE TITLE
allowed_domain(s) in upstream config

### ISSUE THREAD

**Issue by victornoel** [buzzfeed/sso#162]
**Is your feature request related to a problem? Please describe.**

This is a followup on #113 and #161, it would make sense to be able to define access rights directly at the route level for domain instead of globally in order to get a finer control of access restrictions.

Actually, this is not restricted to only one domain, it should be possible to allow for multiple domains, in the same way one can accept mutiple groups or multiple users (see #161).

**Describe the solution you'd like**

Add an `allowed_domains` property at the route level.

I believe that if a domain is specified, then it should override `allowed_groups` and `allowed_users` (in the same way as https://github.com/buzzfeed/sso/issues/161#issuecomment-467622129)

**Describe alternatives you've considered**

Instantiating multiple instance of ssoctopus: it would be painful :)

**Comment by Jusshersmith** [comment]
Hey @victornoel.

Thanks for sending this through. I think https://github.com/buzzfeed/sso/pull/247 should clear this up -- it adds the ability to define allowed email addresses and domains in the upstream config, rather than globally for all upstreams.

Thanks!

**Comment by victornoel** [comment]
@Jusshersmith should I close this issue then?

**Comment by Jusshersmith** [comment]
Ah, yes :-), thank you!

**Comment by victornoel** [comment]
@Jusshersmith hehe, thanks btw for the feature :)
