### ISSUE TITLE
Fix docker image build pipeline

### ISSUE THREAD

**Issue by naseemkullah** [buzzfeed/sso#172]
Please see title, let me know if I can help!

**Comment by jphines** [comment]
Pushed a new image to docker hub for v1.2.0 manually, but seems our automation there has broken. :/ 

Will look into getting this restored.

**Comment by naseemkullah** [comment]
Thanks!
I've changed the issue name accordingly.

**Comment by danbf** [comment]
@katzdm hey can we manually update `latest` as well with the last release until this is all squared away?

**Comment by Jusshersmith** [comment]
The docker image build pipeline has been altered a number of times since this was opened, but seemed to work as expected during the more recent releases.
