### ISSUE TITLE
Proxy attempts to normalize encoded slash by issuing http 301 redirect

### ISSUE THREAD

**Issue by AndrewDryga** [buzzfeed/sso#175]
**Describe the bug**
We have a RabbitMQ management running behind SSO proxy, but we noticed that some pages would not work behind proxy versus using kubectl port forward.

I believe the main reason is that SSO proxy attempts to normalize request path, initially RabbitMQ issues request to: `https://foo/api/exchanges/%2F/amq.direct?msg_rates_age=3600&msg_rates_incr=60` (notice `/%2F/` in URL which can be accidentally read by proxy as `///` and normalized to `/`).

Then proxy issues a HTTP 301 redirect to `/api/exchanges/amq.direct?msg_rates_age=3600&msg_rates_incr=60`. Notice that `/%2F/` is missing here.

This clearly does not happen when connecting to management UI via port forward.

**Expected behavior**
Proxy should forward requests as-is without trying to decode and normalize path.

**Comment by AndrewDryga** [comment]
I think to test it you can setup any page with `/%2F/` in path and open it in any browser.

**Comment by jphines** [comment]
:wave: I can confirm this behavior in SSO and have at least validated is not being added by the stdlib itself. I need to do a little more digging before I would feel comfortable triaging this as a "feature" or a "bug".

**Comment by AndrewDryga** [comment]
Looks more like a bug to me as it breaks our stuff 😃.

**Comment by jphines** [comment]
Actually, after looking into the SSO repo a bit more, I couldn't find anything that would be contributing to this behavior.

After more investigation, this is happening from the Go's standard libraries `ServeMux` implementation. https://golang.org/pkg/net/http/#ServeMux

See a full example here: https://play.golang.org/p/H2Br99jNcwT

 And see a more explicit example shows this is coming from the way the Go standard [library parses the request](https://golang.org/src/net/http/request.go#L1005), [the mux cleans the URL path](https://golang.org/src/net/http/server.go#L2327), and the way the [redirect handler parses and re-cleans the url](https://golang.org/src/net/http/server.go#L2051).  

Condensed Example: https://play.golang.org/p/Lo5Xh88mZbR

To "fix", we'd have to drop support for Go's standard `ServeMux` and be very sensitive of our URL handling to ensure that these potentially malformed URLs are proxied correctly.

This might be a potential path in the future, but for now, this seems to be working as intended. I'd suggest opening an issue against golang itself to see if you can update the standard library logic, or against rabbitmq to change these problematic URLs.

**Comment by AndrewDryga** [comment]
@jphines do you have ideas how we could workaround this for time being? Maybe some configuration change would disable that routine for certain paths?

RabbitMQ development team is known in terms of their "maintenance" and they won't ever consider doing this change. Going trough Go would be a really hard path including we don't have Go developers able to contribute this PR and SSO this project would need to update to the latest Go version even if it gets through.

**Comment by AndrewDryga** [comment]
Also, https://github.com/golang/go/issues/19481
