### ISSUE TITLE
Docker images aren't being tagged with <latest>

### ISSUE THREAD

**Issue by benjsto** [buzzfeed/sso#193]
**Describe the bug**
Both `buzzfeed/sso:latest` and `buzzfeed/sso-dev:latest` are months old at this point.

**To Reproduce**
Pull `buzzfeed/sso:latest` and `buzzfeed/sso-dev:latest` and look at their ages.

```
buzzfeed/sso-dev      latest        54916c0d5a18        3 months ago        96.5MB
buzzfeed/sso          latest        7b02fc301dec        5 months ago        83.8MB
```

**Expected behavior**
When there are new releases, both `sso:latest` and `sso-dev:latest` should point to that release.

**Comment by benjsto** [comment]
For now, I've manually tagged our latest release (v1.2.0) as `latest` in both `buzzfeed/sso` and `buzzfeed/sso-dev`. We'll evaluate how to apply `latest` on an ongoing basis.

**Comment by Jusshersmith** [comment]
👋 I’ve merged https://github.com/buzzfeed/sso/pull/220  which should help with this. 

- With each master commit an image tagged with `:latest` will be pushed to `sso-dev`, as well as the already existing `:<commit>` tagged image.

- The Makefile `releasepush` task will also push a `:latest` tag to `sso`, as well as the already existing `:<version>` tagged image (the running of that is part of the release process).

This should keep them both appropriately up to date!

**Comment by benjsto** [comment]
Thanks @Jusshersmith !
