### ISSUE TITLE
Configure Proxy Cookie Name from Env Var

### ISSUE THREAD

**Issue by alexbakerdev** [buzzfeed/sso#197]
**Is your feature request related to a problem? Please describe.**
Generally this is just making it possible to set the proxy CookieName via the environment.

One scenario where its useful is having multiple auth environments for a single cookie domain (like staging and production subdomains). E.g.

| Cookie Name | Domain |
|---|---|
| _sso_proxy_staging|  `staging.example.com` |
| _sso_proxy |  `example.com` |

Now the staging proxy can read a valid token from the cookies of the request 

**Describe the solution you'd like**
Make the cookie name configurable via an environment variable.

**Describe alternatives you've considered**
N/A

**Comment by jphines** [comment]
Closed by #198
