### ISSUE TITLE
switch to using alpine or a smaller container

### ISSUE THREAD

**Issue by danbf** [buzzfeed/sso#20]
switch to using alpine or a smaller container, like golang:1.9-alpine

**Comment by aiman-alsari** [comment]
Just a note, I built the image using alpine and couldn't replicate the issue described in #22:

> Apparently something about the alpine image prevents the pure Go DNS resolver from properly reading /etc/hosts, which breaks the quick start:
> https://groups.google.com/d/msg/golang-nuts/G-faJ0bthz0/Lx-MsDIOCAAJ

Is it possible this has been fixed by an alpine update, or is there some specific code path I'm not testing?
@mccutchen any thoughts?
