### ISSUE TITLE
Auth for Multiple Domains

### ISSUE THREAD

**Issue by dlmiddlecote** [buzzfeed/sso#201]
Hi,

I was wondering whether there was any information or prior art to allowing auth to happen upon 2 domains within the same kubernetes cluster?

Do I just have to run 2 versions of sso, or is there a way to configure sso to support multiple domains?

**Comment by weeco** [comment]
Just put multiple domains separated by a comma into your email domain variable.

**Comment by jphines** [comment]
@dlmiddlecote Are you referring to proxy domains or email domains used for authorization?

As @weeco mentions, you can use commas to separate multiple email domains or the wildcard `*` to allow any domains.

**Comment by dlmiddlecote** [comment]
Hey @jphines I’m referring to proxy domains, i.e `foo.com` and `foo.net`, both of which will use the same google accounts to login.

**Comment by jphines** [comment]
@dlmiddlecote you can use a CSV separated list of domains to configure the env var for `PROXY_DOMAINS`

We use this configuration to specify proxy root domains such as: `buzzfeed.com,tasty.co,buzzfeednews.com` etc.

**Comment by dlmiddlecote** [comment]
Cool, I’ll try it out. Thanks @jphines
