### ISSUE TITLE
Question in regards to attempting to CNAME service.sso.example.com with a more user friendly url

### ISSUE THREAD

**Issue by btai24** [buzzfeed/sso#219]
I would like to have my service urls be service.example.com instead of service.sso.example.com but even if I create a CNAME record to point service.example.com -> service.sso.example.com, it'll be routed with service.example.com as the host, meaning it won't hit the sso-proxy (*.sso.example.com) 

I read in this blog that buzzfeed is achieving what I want to do: https://tech.buzzfeed.com/unleashing-the-a6a1a5da39d6

Specifically this line:
```
* In practice, we usually create a more user-friendly domain like ghost-land.pacworld.com that points to ghost-land.sso.pacworld.com.
```

I was curious how your team is achieving that?

**Comment by jphines** [comment]
👋 @btai24 

We setup our routes and dns such that request to `service.example.com` _will_ hit the sso-proxy.


## Vanity Domain Example
So in a made-up example:
```bash
$ dig example.buzzfeed.com

; <<>> DiG 9.8.3-P1 <<>> example.buzzfeed.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35316
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;example.buzzfeed.com.		IN	A

;; ANSWER SECTION:
example.buzzfeed.com.	108	IN	CNAME	sso-proxy.corp.buzzfeed.com.
sso-proxy.corp.buzzfeed.com. 59	IN	A	54.204.176.132
sso-proxy.corp.buzzfeed.com. 59	IN	A	54.85.189.199
sso-proxy.copr.buzzfeed.com. 59	IN	A	34.205.249.29

;; Query time: 14 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jun 25 10:08:53 2019
;; MSG SIZE  rcvd: 122
```

`example.buzzfeed.com` here is a cname to `sso-proxy.corp.buzzfeed.com`.

Internally, the `example` service may have a different hostname that we can use to reverse proxy requests through sso, such as `example.internal.buzzfeed.com`

So an sso proxy config might look like:

```yaml
- service: example service
  default:
    from: example.buzzfeed.com
    to: example.internal.buzzfeed.com
```

We typically refer to this type of configuration as a vanity configuration.

## Wildcard Example

Most often, we use a wildcard configuration so we don't have to manage as many vanity domains. In this example, we use:

```bash
$ dig example.sso.buzzfeed.com

; <<>> DiG 9.8.3-P1 <<>> example.sso.buzzfeed.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32466
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;example.sso.buzzfeed.com.	IN	A

;; ANSWER SECTION:
example.sso.buzzfeed.com. 299 IN	CNAME	sso-proxy.corp.buzzfeed.com.
sso-proxy.corp.buzzfeed.com. 59	IN	A	54.165.184.109
sso-proxy.corp.buzzfeed.com. 59	IN	A	34.233.101.10
sso-proxy.corp.buzzfeed.com. 59	IN	A	52.72.172.70

;; Query time: 22 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Tue Jun 25 10:15:52 2019
;; MSG SIZE  rcvd: 119
```

Here, the example configuration is just a wildcard record we've setup for `*.sso.buzzfeed.com`, so any wildcard address will resolve to `sso-proxy.corp.buzzfeed.com`.

For this, an example configuration might look like:

```yaml
- service: example service
  default:
    from: example.sso.buzzfeed.com
    to: example.internal.buzzfeed.com
```

which isn't all that different!

SSO isn't particularly concerned with _how_ you manage your dns routing, as long as it as a well-defined set of domains to reverse proxy _from_ and _to_.

**Comment by btai24** [comment]
@jphines I see, I have deployed this on kubernetes and so even if I CNAME example.buzzfeed.com to  example.sso.buzzfeed.com, the ingress controller will send the request to the example.buzzfeed.com service instead of my sso-proxy service (which expects requests from hosts like *.sso.buzzfeed.com). If you are using kubernetes, have you guys ran into this scenario? Did you need to configure the ingress controller to rewrite the host header?

**Comment by btai24** [comment]
@jphines I was stuck on the idea having to use "*.sso.buzzfeed.com". I went with the vanity domain approach and ditched the wildcard domain (we only have a few services in this cluster). works great thanks!
