### ISSUE TITLE
Error loading env file 

### ISSUE THREAD

**Issue by blucompassai** [buzzfeed/sso#222]
**Describe the bug**
Followed quickstart guide and when did docker-compose up it , only sso-auth container is not coming up and giving this error :

{"error":"2 error(s) decoding:\n\n* 'client[id]' expected a map, got 'string'\n* 'client[secret]' expected a map, got 'string'","level":"error","msg":"error loading in config from env vars","service":"sso-authenticator","time":"2019-06-28 07:57:42.105"}

**To Reproduce**
Just follow the quickstart guide.
- I am on ubuntu 
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch

- docker version
docker --version
Docker version 18.09.7, build 2d0083d
docker-compose --version
docker-compose version 1.21.2, build a133471

- env file 
CLIENT_ID=<value>
CLIENT_SECRET=<value>

**Expected behavior**
Expected sso-auth to come up

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Comment by tarpdalton** [comment]
It looks like #213 made the config pretty different. If you switch to the stable docker image it should work. `image: buzzfeed/sso:v1.2.0`

**Comment by Jusshersmith** [comment]
Hi @blucompassai.

How did you get on with @tarpdalton's (thank you @tarpdalton!) suggestion? 

Also, just so you're aware; version `2.0.0` has now been released (https://github.com/buzzfeed/sso/releases/tag/v2.0.0) which includes a lot of configuration changes (including the one that was causing what you saw). Please let us know if you have any issues with the new setup.

**Comment by tl-alexandre-kaskasoli** [comment]
It would be great to have some updated docs for deploying on Kubernetes. The blog post the docs point is outdated.
