### ISSUE TITLE
sso-auth throwing 404

### ISSUE THREAD

**Issue by mcfearsome** [buzzfeed/sso#237]
**Describe the bug**
After being redirected to my sso-auth endpoint I am receiving a 404 message and the following log:
```
{"action":"unknown","http_status":404,"level":"info","msg":"","proxy_host":"kibana.sso.staging.egdod.weblinc.com","remote_address":"68.81.187.115","request_duration":0.05432,"request_method":"GET","request_uri":"/google/sign_in?client_id=eS93Unkvc1BlQ1dtUzZrd0ZhdUgyTmlVQ1ZNUVphZEk%3D\u0026redirect_uri=http%3A%2F%2Fkibana.sso.staging.egdod.weblinc.com%2Foauth2%2Fcallback\u0026response_type=code\u0026scope=\u0026sig=5o83AFT_kzyIEyavvYaHnCzYWSgdRKg4ciz7YZXlcP4%3D\u0026state=f_LWAAXKn3fvi0U4WukGECSHS-45KPtTO_TwM22Nz6M-xwxv7-GrUc-Ckc3gA7ZTEugxuivj3WvuwHjKsW7I_MkCQ2nVu8meZrq1nec5ebtl2KCeofNJ1JQfZ1znhJxoY4y6dqyJOCIapkXVibp9r88EpMFFupMJmbFOSode7HDCMuIirU1VcpKYJv4xZFg\u0026ts=1564797612","service":"sso-authenticator","time":"2019-08-03 02:00:29.832","user":"","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36"}
```

**To Reproduce**
Followed https://medium.com/@while1eq1/single-sign-on-for-internal-apps-in-kubernetes-using-google-oauth-sso-2386a34bc433 
Using `buzzfeed/sso:v1.2.0` as image after encountering another issue with the client_id/secret

**Expected behavior**
I expect to be prompted to login

**Additional context**
I believed maybe network policies were interfering but have opened up both ingress and egress to both deployments.  I feel like I must have done something wrong but cannot seem to determine what based on the log output.

**Comment by mcfearsome** [comment]
please disregard, I failed to update the image tag for the proxy deployment

**Comment by omerxx** [comment]
@mcfearsome Hey there, kind of a long shot but experiencing the same with the latest release and this is the only reference I could find. Any idea what went wrong other than the image version?
I'm using latest build tags for both the proxy and the authenticator
