### ISSUE TITLE
auth: How do you specify SERVER_TIMEOUT_REQUEST?

### ISSUE THREAD

**Issue by cameronattard** [buzzfeed/sso#239]
When setting `SERVER_TIMEOUT_REQUEST` as an environment variable with a value such as `60000`, `auth` returns the following error: `panic: interface conversion: interface {} is json.Number, not string`. What is the correct way to configure this option?

**Comment by Jusshersmith** [comment]
Hey @cameronattard.

I believe it should be set as a `time.Duration` https://golang.org/pkg/time/#Duration, e.g: `5s`. Here are the defaults we set: https://github.com/buzzfeed/sso/blob/14f2a962d995bbd4b69da4420df5fe53dc3468c2/internal/auth/configuration.go#L75-L79

I can also understand that that's not abundantly clear right now, so I apologise! I'll work on clearing that up.

**Comment by Jusshersmith** [comment]
https://github.com/buzzfeed/sso/pull/240 should have hopefully made the available configuration settings for `sso_auth` a little bit clearer! Please let us know if that's not the case!
