### ISSUE TITLE
Invalid configuration: missing setting (v2.0.0)

### ISSUE THREAD

**Issue by LanceSandino** [buzzfeed/sso#242]
Using kubernetes to deploy sso-proxy, currently on v1.2.0

We changed the image to the latest v2.0.0 and updated the env variables.

We then get the following error:

`{"error":"Invalid configuration:\n  missing setting: cookie-secret\n  missing setting: client-id\n  missing setting: client-secret\n  missing setting: statsd-host\n  missing setting: statsd-port\n  Invalid value for COOKIE_SECRET; must decode to 32 or 64 bytes, but decoded to 0 bytes","level":"error","msg":"error validing options","service":"sso-proxy","time":"2019-08-12 15:18:49.820"}
`

**Comment by LanceSandino** [comment]
If I re-add `COOKIE-SECRET` `CLIENT-ID` `CLIENT-SECRET` `STATSD-HOST` and `STATSD-PORT` it works just fine.


It also seems that v2.0 fixes the issue I had: https://github.com/buzzfeed/sso/issues/228 ?

**Comment by Jusshersmith** [comment]
Hi @LanceSandino 

Apologies for not making this clearer in the release notes, however the majority of configuration variable changes introduced in **v2.0.0** only apply to `sso_auth` (_not_ `sso_proxy`). It looks like these particular changes were made to the sso_proxy component.

I've updated the release notes to make this clearer. (previously, it would've been mostly evident after looking at the PR referenced in the release notes!)

Similar changes will eventually be made to sso_proxy as well!

Sorry for any inconvenience this caused!

**Comment by Jusshersmith** [comment]
Hi @LanceSandino

Apologies for not making this clearer in the release notes, however the majority of configuration variable changes introduced in v2.0.0 only apply to sso_auth (not sso_proxy). It looks like these particular changes were made to the sso_proxy component.

I've updated the release notes to make this clearer. (previously, it would've been mostly evident after looking at the PR referenced in the release notes!)

Similar changes will eventually be made to sso_proxy as well!

Sorry for any inconvenience this caused, and thank you for raising!
