### ISSUE TITLE
Allow injection of request headers in proxy

### ISSUE THREAD

**Issue by mcfearsome** [buzzfeed/sso#243]
**Is your feature request related to a problem? Please describe.**
I am setting sso up in front of a Kibana instance that is created using the ECK operator.  This does not allow me to turn off the xpack security feature (I can on Kibana but am unable to for Elasticsearch which causes issues for Kibana).  In order to avoid having the user login twice I would like to be able to include the basic auth credentials in the upstream config.

**Describe the solution you'd like**
Add new option to the `UpstreamConfig` similar to `HeaderOverrides`

**Describe alternatives you've considered**
I could not use the ECK operator and run ES without any security at all, would prefer to not do that

**Comment by jphines** [comment]
@mcfearsome I believe setting `HeaderOverrides` will work in this case to inject new headers. Does it not?

**Comment by mcfearsome** [comment]
@jphines `HeaderOverrides` looks to be for Response Headers not adding onto the request before it hits the proxied service. I have a PR incoming (never wrote Go before so go easy)

**Comment by mcfearsome** [comment]
Just to make sure I wasn't being dumb I double checked using `HeaderOverrides` with the current value that is working with `InjectRequestHeaders` and it does not work (but is present in the Response Headers)
