### ISSUE TITLE
add a new parameter which overrides the `PROVIDER_URL` for the sso-proxy->sso-auth connection for split dns environments

### ISSUE THREAD

**Issue by danbf** [buzzfeed/sso#26]
add a new parameter which overrides the `PROVIDER_URL` for the sso-proxy->sso-auth connection for split dns environments

currently the `PROVIDER_URL` is both used to generate the sign_in url for the client `http://sso-auth.localtest.me/sign_in?` and by the sso-proxy for the redeem transaction `http://sso-auth.localtest.me/redeem`.  In a split DNS environment they point to different IP's as is the case with the current quickstart.

currently `sso-auth.localtest.me` resolves to different IP's for the client and the sso-proxy process:

for `PROVIDER_URL=sso-auth.localtest.me`
Client Resolution: sso-auth.localtest.me=127.0.0.1
sso-proxy Resolution: sso-auth.localtest.me=172.20.0.1 which forced by https://github.com/buzzfeed/sso/blob/master/quickstart/docker-compose.yml#L64-L65 and https://github.com/buzzfeed/sso/blob/master/quickstart/docker-compose.yml#L137-L143

i propose an optional parameter `PROXY_PROVIDER_URL` which when present is used by the sso-proxy to generate the redeem transaction url.  when not present the current behavior of `PROVIDER_URL` being used.  ideally this would result in:

for `PROVIDER_URL=sso-auth.localtest.me`
for `PROXY_PROVIDER_URL=host.docker.internal`
Client Resolution: sso-auth.localtest.me=127.0.0.1
sso-proxy Resolution: host.docker.internal=172.20.0.1
with out the need for any docker-compose `extra_hosts` or `networks` stanza's

**Comment by tyrken** [comment]
FYI just hit this in an AWS K8s deploy, and glad I saw you'd already started before i try my own PR.  I'm wanting cluster-internal traffic between sso-proxy and sso-auth to stay inside the cluster, not need to go out & back in via the locked down external ingress.

**Comment by danbf** [comment]
resolved in https://github.com/buzzfeed/sso/pull/88
