### ISSUE TITLE
ERROR: Service 'sso-proxy' failed to build: The command '/bin/sh -c go mod download' returned a non-zero code: 1 

### ISSUE THREAD

**Issue by lakshaytalkstocomputer** [buzzfeed/sso#288]
**Describe the bug**
I swapped the lines in docker-compose.yml  "#image: buzzfeed/sso-dev:latest" -> "build: .."

**To Reproduce**
1. Follow Quickstart guide.
2. Before docker-compose up -d , swap the lines in docker-compose.yml
3. Run docker-compose up -d.

**Expected behavior**
Running smoothly quickstart guide.

**Screenshots**
![Screenshot from 2020-03-12 14-02-07](https://user-images.githubusercontent.com/38259381/76502479-1895c180-646a-11ea-8cf1-505e1feae902.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 18.0

**Comment by Jusshersmith** [comment]
Hi @lakshaytalkstocomputer! Thanks for opening this issue, and sorry you've been running into some problems.

I'm afraid however I can't replicate this anymore - are you still running into this on your end?

**Comment by Jusshersmith** [comment]
HI @lakshaytalkstocomputer. Please feel free to reopen this if you're still having difficulty with this! It looks like it might've been an issue with a specific dependency at the time.
