### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by benmccann** [buzzfeed/sso#302]
https://github.com/buzzfeed/sso/blob/master/docs/sso_config.md says "This signs the request using defined signature headers found in https://github.com/buzzfeed/sso/blob/master/sso_proxy/oauthproxy.go#L25." but that link is broken

On the next line it links to https://github.com/18F/hmacauth which has been archived and mostly just says "coming soon" on its readme

**Comment by Jusshersmith** [comment]
Hey @benmccann. Closing this, as it was fixed in https://github.com/buzzfeed/sso/pull/315 (The line numbers themselves are likely to change, so the variable name itself has also been referenced, as this is much less likely to change)
