### ISSUE TITLE
Create Updated Docker Image

### ISSUE THREAD

**Issue by dpeckett** [buzzfeed/sso#311]
The Docker image has not been rebuilt since the last release in 2019, this means it contains a variety of security erratas.

Can you perform a new Docker build or create a new release of the project.

**Comment by matthias-kloeckner** [comment]
just asking kindly: do you have an estimation for this?

**Comment by Jusshersmith** [comment]
Apologies for the slow turnaround here. I'll look to publish a new release by the end-of-day Friday, however hopefully sooner! 

Thank you for your patience!

**Comment by Jusshersmith** [comment]
Just in case it was missed, a new `3.0.0` version was released earlier today. This includes a variety of changes, including large alterations to the configuration variables used by `sso_proxy`, so please take care while updating. 🙂

**Comment by mirobertod** [comment]
@Jusshersmith thank you for the new release

It looks like after upgrade to v3.0.0 all the requests end up with the `421 Misredirect request`; even the quickstart is not working anymore.

**Comment by Jusshersmith** [comment]
Hey @mirobertod. 

If you change https://github.com/buzzfeed/sso/blob/main/quickstart/docker-compose.yml#L37 to `UPSTREAM_CONFIGFILE`, and restart the containers, does that help at all? (note the `S` has been removed in 'CONFIGFILE').

**Comment by mirobertod** [comment]
Hi @Jusshersmith 
I can confirm that now using the env var `UPSTREAM_CONFIGFILE` without the `S` is working fine.

Thanks

**Comment by Jusshersmith** [comment]
Great! A fix has been opened: https://github.com/buzzfeed/sso/pull/286. 

Please do open up a new issue if you run into any other errors. Now that the release is out, I'll close this one 👍
