### ISSUE TITLE
sso-auth: add support for individual e-mail address authentication

### ISSUE THREAD

**Issue by starcraft66** [buzzfeed/sso#32]
**Is your feature request related to a problem? Please describe.**
Currently, it is only possible to whitelist an entire domain of addresses, which is convenient for organizations, however it is not so convenient for single users wishing to authenticate oAuth on a public domain such as gmail.com.

**Describe the solution you'd like**
It would be nice if there was a configuration option to specify a list of individual e-mail addresses to whitelist, or a path to a file containing a list of emails to whitelist, in addition to optionally also specifying whitelisted domain(s).

**Describe alternatives you've considered**
I haven't considered any alternatives whitelisting methods because Google is the only oAuth provider currently supported.

**Additional context**
This feature was already available in oauth2_proxy via the "authenticated-emails-file" command-line flag.

**Comment by tahoward** [comment]
I would like to see this implemented as well. Use case would be for personal services that don't require $5 a month for G Suite.

**Comment by shrayolacrayon** [comment]
Hi! Thank you for opening. This is something that we do not internally have the bandwidth to implement but we are always open to merging in open source contributions!  To me this would look something like creating a new [provider](https://github.com/buzzfeed/sso/blob/master/internal/auth/providers/providers.go#L33) that uses [htpasswd](https://httpd.apache.org/docs/2.4/programs/htpasswd.html) in its implementation.

**Comment by mreiferson** [comment]
See #113

**Comment by benjsto** [comment]
This was done in https://github.com/buzzfeed/sso/pull/113.
