### ISSUE TITLE
Is this project still maintained? 

### ISSUE THREAD

**Issue by jakubbujny** [buzzfeed/sso#340]
Last commit is 2 years old. Should that project be forked and then continued?

**Comment by notnmeyer** [comment]
im not affiliated with the project, but i think you probably know the answer to your question already. no one should be comfortable using an abandoned auth proxy to protect any internet-facing services.

**Comment by cincauhangus** [comment]
pretty sure there's no buzzfeed engineering anymore

**Comment by o6uoq** [comment]
If the project was still maintained by BuzzFeed, I'd expect to see a listical like "7 Top Project Maintainers - Which One Are You?"
