### ISSUE TITLE
Metrics configuration should be optional

### ISSUE THREAD

**Issue by mccutchen** [buzzfeed/sso#35]
Both `sso-auth` and `sso-proxy` refuse to start without `STATSD_HOST` and `STATSD_PORT` env vars, but — especially while we only support the DataDog statsd client — metrics reporting should be optional and disabled in the absence of those config values.

**Comment by mccutchen** [comment]
While we're at it, what if we also combine those vars into a single `STATSD_ADDR="host:port"` configuration?  Are there downsides to a combined value in terms of ease of configuration in different operating environments?

**Comment by multani** [comment]
Duplicate of #5 :)

**Comment by sporkmonger** [comment]
I generally prefer `host:port` config style, FWIW.

**Comment by mccutchen** [comment]
@multani ha, thanks, you're right!  Closing in favor of #5!
