### ISSUE TITLE
sso-auth: refactor Provider-related tests

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#4]
## What
* Remove `ProviderData` as an implementation of the `Provider` interface
* Change unit tests in authenticator.go to use `TestProvider` as mock
* Some tests use the google provider and test the Authenticator behavior with those. We should keep those, but possibly separate them out. 

## Why
Our tests inconsistently use `TestProvider`, a mock of the `Provider` interface and [`ProviderData` ](https://github.com/buzzfeed/sso/blob/master/internal/auth/providers/provider_default.go) which is an inconsistent implementation of the Provider interface, returning an `ErrNotImplemented` for some functions, but not for all.

**Comment by shrayolacrayon** [comment]
Closing this as we have made changes to our providers and updated tests accordingly.
