### ISSUE TITLE
Simplify secret validation code

### ISSUE THREAD

**Issue by mccutchen** [buzzfeed/sso#40]
In #37, I covered some of the difficulties I encountered in generating a valid secret.  A lot of the complexity arises from the fact that sso accepts either base64-encoded bytes or raw bytes, and attempt to guess which it has been given.

Unfortunately, that guess is extremely unreliable, because
 - It will reject legitimate raw secret bytes that _happen_ to decode as base64
 - The base64 decoder used will not decode the output of the `base64` CLI tool a user might naturally reach for to safely encode a set of randomly generated bytes

Here are some legitimate secret values that will be rejected:

```bash
# 32 ASCII bytes generated by 1Password
H3LWy8KF86hm2UcE3XAYvb2ub2G33YiV

$ openssl rand 32 -base64
AquwB7PgQRVaAFKwEXDefRhfegtqfLXVP4/LbDSHkpY=

$ openssl rand 32 | base64
4QkZXXwT27g4tYbdO50gA0UHo5S8OElg0Vs0m+E5w1c=
```

I can't remember why there's so much flexibility built into the secret validation code, but it feels too complex:
https://github.com/buzzfeed/sso/blob/9f61688d4cd0c6252fa347386c64b90eff4cc4fd/internal/auth/options.go#L175-L194

And it seems like this code should be stricter about what it will accept, and rely on the application  to provide secret bytes in some specific form:
https://github.com/buzzfeed/sso/blob/9f61688d4cd0c6252fa347386c64b90eff4cc4fd/internal/pkg/sessions/cookie_store.go#L50-L57

**Comment by mreiferson** [comment]
Looks like this landed in #56, closing!
