### ISSUE TITLE
sso-proxy: remove deprecated session unmarshal code and old cookie secrets

### ISSUE THREAD

**Issue by shrayolacrayon** [buzzfeed/sso#42]
**Why**
We have two code paths for loading the session state in `sso-proxy` that we kept in until the cookie refresh period expired for sso in production. Both code paths were kept in place so that having an invalidly decrypted session cookie would not affect the UX for those logging into sso-proxy with the sessions encrypted the old way.  We can now remove that code path. 

This will involve removing:
- `OldCookieCipher` and `OldCookieSecret` from the `OAuthProxy` [struct](https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L59). 
- [initialization logic] for old cookie secrets and ciphers (https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L249) in `NewOAuthProxy`
- [`ErrRefreshCookie`](https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L921)
- fallback of using old cookie cipher  in [`LoadCookiedSession`](https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L491)

**Comment by loganmeetsworld** [comment]
Handled in https://github.com/buzzfeed/sso/pull/54
