### ISSUE TITLE
Support a configuration option akin to mod_proxy's ProxyPreserveHost

### ISSUE THREAD

**Issue by sporkmonger** [buzzfeed/sso#52]
Currently SS Octopus replaces the Host header provided by the client with a new Host header based on the upstream DNS name. It also isn't very careful in how it sets the `X-Forwarded-Host` header (adds a new one, ignoring any that may have been set by another proxy or networking component). In some configurations, particularly those involving other proxies or servers that have virtual hosts, it's desirable to preserve the client-provided host. This should be a per-upstream configuration option.

**Comment by mreiferson** [comment]
See #55
