### ISSUE TITLE
sso-auth: decouple setting provider with options validation

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#6]
## What 
Move out initializing providers from validating Options into to a separate function that can be taken in as an option function. 
## Why 
Currently we set the provider as the google provider during [validation](https://github.com/buzzfeed/sso/blob/master/internal/auth/options.go#L176) of the `Options` struct which makes it difficult to add a new provider and to add new features to existing providers. Decoupling the logic from validating Options will make it simpler to support adding new providers.

**Comment by sporkmonger** [comment]
I've started working on this.

**Comment by shrayolacrayon** [comment]
Sounds great, what is the approach you are planning to take in refactoring and decoupling the logic?

**Comment by sporkmonger** [comment]
I think I'll probably start by flagging sections of code that I think will be affected and linking them here for discussion.

**Comment by sporkmonger** [comment]
Potentially I think this could be two refactor PRs, one for options cleanup, one for validation & ID token prep work.
