### ISSUE TITLE
sso-auth: fails to starts with error "bad key size"

### ISSUE THREAD

**Issue by akshayatplivo** [buzzfeed/sso#66]
**Describe the bug**
Running "sso-auth" results in : 

```
> {"error":"siv: bad key size","level":"error","msg":"","service":"sso-authenticator","time":"2018-09-21 11:56:10.92111"}
> {"error":"siv: bad key size","level":"error","msg":"error creating new Authenticator","service":"sso-authenticator","time":"2018-09-21 11:56:10.92111"}
> 
```

**To Reproduce**
Follow the steps provided in the URL : 

https://github.com/buzzfeed/sso/blob/master/docs/google_provider_setup.md

and generate the google json

**Expected behavior**
sso-auth service should launch without errors. 

**Additional context**
This is running on Ubuntu 18.04. However "sso-proxy" starts without errors.

**Comment by shrayolacrayon** [comment]
Hi @akshayatplivo, thank you for opening this issue! 
I'd like to get some more information about your set-up process to try to help. Are you following the quickstart [guide](https://github.com/buzzfeed/sso/blob/master/docs/quickstart.md) to get `sso` set up, and if not, can you describe what steps you have taken in your setting-up process?

**Comment by gorilych** [comment]
@akshayatplivo 

This error may be related to seed strings. Make sure that AUTH_CODE_SECRET is generated with `openssl rand -base64 32 | head -c 32 | base64`

@shrayolacrayon 

I believe sso-auth should check AUTH_CODE_SECRET the same way it checks COOKIE_SECRET, see lines https://github.com/buzzfeed/sso/blob/3a64e696452e2fea5d571e63ad5a53e45694ecd1/internal/auth/options.go#L177 till line 191

**Comment by bertjwregeer** [comment]
This error happens if the value for `AUTH_CODE_SECRET` is not set or is missing entirely.

**Comment by Jusshersmith** [comment]
This is an old issue, and the relevant logic has changed a lot since it was opened (and in fact, further checks and clearer errors have been added) -- closing this off.
