### ISSUE TITLE
build static assets into go binary

### ISSUE THREAD

**Issue by loganmeetsworld** [buzzfeed/sso#7]
**Is your feature request related to a problem? Please describe.**
Currently, static assets are not built into the binary.

**Describe the solution you'd like**
We can build the static assets into the go binary to make it easier to pull and use the Docker image without needing to mount the static directory. 
We can use [go-bindata](https://github.com/jteeuwen/go-bindata) to compile static images into our go binary, similar to what is done in [go-httpbin](https://github.com/mccutchen/go-httpbin)

**Comment by sporkmonger** [comment]
I'm putting together a PR for this.

**Comment by sporkmonger** [comment]
PR's ready to go.
