### ISSUE TITLE
BUZZFEED_SSO_CONFIG variables not being interpolated in upstream_configs.yml

### ISSUE THREAD

**Issue by notnmeyer** [buzzfeed/sso#97]
i'm trying to template my `upstream_configs.yml` as described here, https://github.com/buzzfeed/sso/blob/master/docs/sso_config.md. sso-proxy never seems to come up cleanly when I try. for example, here's a diff demonstrating my issue using the quickstart stuff:

```
diff --git a/quickstart/docker-compose.yml b/quickstart/docker-compose.yml
index ec9b285..2fe9d79 100644
--- a/quickstart/docker-compose.yml
+++ b/quickstart/docker-compose.yml
@@ -53,6 +53,8 @@ services:

       # Tells nginx-proxy service how to route requests to this service
       - VIRTUAL_HOST=*.sso.localtest.me
+
+      - BUZZFEED_SSO_CONFIG_HTTP_BIN=httpbin
     volumes:
       - ./upstream_configs.yml:/sso/upstream_configs.yml:ro
     expose:
diff --git a/quickstart/upstream_configs.yml b/quickstart/upstream_configs.yml
index 0991787..385e397 100644
--- a/quickstart/upstream_configs.yml
+++ b/quickstart/upstream_configs.yml
@@ -1,7 +1,7 @@
 - service: httpbin
   default:
     from: httpbin.sso.localtest.me
-    to: http://httpbin:8080
+    to: http://{{http_bin}}:8080

 - service: hello-world
   default:
```

run `docker-compose up` and you'll get, `sso-proxy_1    | {"error":"Invalid configuration:\n  error parsing upstream configs file unable to url parse `to` parameter error=parse http://{{http_bin}}:8080: invalid character \"{\" in host
name","level":"error","msg":"error validing options","service":"sso-proxy","time":"2018-10-23 16:19:26.10234"}`

am i missing something obvious here?

**Comment by xoob** [comment]
It's because the prefix should be `SSO_CONFIG_` not `BUZZFEED_SSO_CONFIG_`. The docs need to be updated.

https://github.com/buzzfeed/sso/blob/1662f7cc129421a9d2ac8aff577823bbd3703ec8/internal/proxy/options.go#L271
