### ISSUE TITLE
sso-auth: support okta as provider 

### ISSUE THREAD

**Issue by shrayolacrayon** [buzzfeed/sso#99]
Add support for Okta as a provider for sso-auth as part of #27

**Comment by paktek123** [comment]
okta is supported now I believe: https://github.com/buzzfeed/sso/blob/master/internal/auth/providers/okta.go ?

**Comment by Jusshersmith** [comment]
Hi @paktek123. It is indeed! We wanted to leave this open until it was included in an official release - which it now has been!
